apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: job-example
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: job-example
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: job-example:latest
    source:
      git:
        uri: git://openshift.example.com/test
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:2.7
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
