apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Job
  metadata:
    name: job-example
  spec:
    selector:
      matchLabels:
        foo: bar
    template:
      metadata:
        labels:
          foo: bar
      spec:
        containers:
        - name: test
          image: 172.30.132.21:5000/demo/job-example
        restartPolicy: Never
